%mem=100GB
%nproc=48
%oldchk=optfreq.chk
%chk=sp.chk
#p MaxDisk=100GB pbe1pbe/genecp em=gd3bj int=fine scf=maxcyc=200 scrf(solvent=water)

Generated by Multiwfn

  3  1
[GEOMETRY]
 
C O N H
def2TZVP
****
Eu
MWB52
****

Eu
MWB52


