#!/usr/bin/env python3
"""
ana_geometry_static.py
----------------------
Static geometry analysis for 9-coordinate Eu complexes from GRO files.

Part A:
  Chimera-style coordination-sphere RMSD to ideal SAP/TSAP.

Part A2:
  Purely geometry-based extended score using 11 points:
    - 9 coordination atoms
    - 2 Tc-link atoms (C17, C24)
  The 2 extra ideal points are generated by geometric projection from a fixed
  reference structure using class-specific Procrustes transforms derived from
  the 9-point ideal fit. No torsion sign rule and no additive penalty are used.

Part B:
  Torsion analysis (T1-T4 and Tc) with sign-based SAP/TSAP classification.
"""

import argparse
import os
import sys

import numpy as np

# =============================================================================
# Configuration
# =============================================================================

METAL_GRO = 55
COORD_GRO = [1, 2, 3, 4, 5, 6, 7, 8, 64]
BOTTOM = [3, 4, 5, 6]
TOP = [0, 1, 2, 7]
CAP = [8]

SAP_TWIST_DEG = -45.0
TSAP_TWIST_DEG = 0.0

RING_TORS = [
    ("T1  N4 -C9 -C10-N5 ", 4, 9, 10, 5),
    ("T2  N5 -C11-C12-N6 ", 5, 11, 12, 6),
    ("T3  N6 -C13-C14-N7 ", 6, 13, 14, 7),
    ("T4  N7 -C15-C16-N4 ", 7, 15, 16, 4),
]
CHROM_TOR = ("Tc  N4 -C17-C24-N8 ", 4, 17, 24, 8)

CLASSIFY_THRESH = 10.0
A2_AMBIG_THRESH_A = 0.05

# Tc inversion helper indices
TC_N4_IDX = 4
TC_C17_IDX = 17
TC_C24_IDX = 24
TC_N8_IDX = 8
TC_H45_IDX = 45
TC_H46_IDX = 46

# Extra atoms added in A2
A2_EXT_GRO = [TC_C17_IDX, TC_C24_IDX]

DUM_NAMES = ["DO1 ", "DO2 ", "DO3 ", "DN4 ", "DN5 ", "DN6 ", "DN7 ", "DN8 ", "DN64"]

# =============================================================================
# GRO I/O
# =============================================================================


def read_gro(path):
    with open(path) as fh:
        lines = fh.readlines()

    title = lines[0].rstrip("\n")
    n_atoms = int(lines[1].strip())

    atoms = []
    for line in lines[2 : 2 + n_atoms]:
        atoms.append(
            dict(
                resnum=int(line[0:5]),
                resname=line[5:10].strip(),
                atomname=line[10:15].strip(),
                atomnum=int(line[15:20]),
                x=float(line[20:28]),
                y=float(line[28:36]),
                z=float(line[36:44]),
            )
        )

    box = lines[2 + n_atoms].rstrip("\n")
    return title, atoms, box


def atoms_to_xp(atoms):
    return np.array([[a["x"], a["y"], a["z"]] for a in atoms], dtype=float)

# =============================================================================
# Geometry helpers
# =============================================================================


def dihedral_deg(p1, p2, p3, p4):
    b1 = p2 - p1
    b2 = p3 - p2
    b3 = p4 - p3
    n1 = np.cross(b1, b2)
    n2 = np.cross(b2, b3)
    nn1 = np.linalg.norm(n1)
    nn2 = np.linalg.norm(n2)
    if nn1 < 1e-9 or nn2 < 1e-9:
        return np.nan
    n1 /= nn1
    n2 /= nn2
    b2n = b2 / np.linalg.norm(b2)
    return float(np.degrees(np.arctan2(np.dot(np.cross(n1, n2), b2n), np.dot(n1, n2))))


def _kabsch_batch(Ps, Q):
    H = np.einsum("kni,nj->kij", Ps, Q)
    U, _, Vt = np.linalg.svd(H)

    dets = np.linalg.det(np.einsum("kij,kjl->kil", Vt.swapaxes(1, 2), U.swapaxes(1, 2)))
    signs = np.sign(dets)

    diag = np.zeros((len(Ps), 3, 3))
    diag[:, 0, 0] = 1.0
    diag[:, 1, 1] = 1.0
    diag[:, 2, 2] = signs

    Rs = np.einsum("kij,kjl,klm->kim", Vt.swapaxes(1, 2), diag, U.swapaxes(1, 2))
    rotated = np.einsum("kni,kji->knj", Ps, Rs)

    diff = rotated - Q[np.newaxis]
    rmsds = np.sqrt(np.mean(np.sum(diff * diff, axis=2), axis=1))
    return rmsds, Rs


def kabsch(P, Q):
    H = P.T @ Q
    U, _, Vt = np.linalg.svd(H)
    d = float(np.sign(np.linalg.det(Vt.T @ U.T)))
    R = Vt.T @ np.diag([1.0, 1.0, d]) @ U.T
    diff = P @ R.T - Q
    rmsd = float(np.sqrt(np.mean(np.einsum("ij,ij->i", diff, diff))))
    return rmsd, R


def procrustes_scale_rotate(source, target):
    """Fit target ~= s * source @ R.T ; source/target assumed centered."""
    _, R = kabsch(source, target)
    src_rot = source @ R.T
    denom = float(np.sum(src_rot * src_rot))
    if denom < 1e-12:
        s = 1.0
    else:
        s = float(np.sum(src_rot * target) / denom)
    return s, R


def get_c4_frame(coord9):
    ring_n = coord9[BOTTOM]
    centroid = ring_n.mean(0)
    _, _, vt = np.linalg.svd(ring_n - centroid)
    z = vt[-1]
    if np.dot(z, coord9[CAP[0]]) < 0:
        z = -z

    cap_vec = coord9[CAP[0]]
    cap_proj = cap_vec - np.dot(cap_vec, z) * z
    cap_norm = np.linalg.norm(cap_proj)
    if cap_norm > 1e-8:
        x = cap_proj / cap_norm
    else:
        tmp = np.array([1.0, 0.0, 0.0]) if abs(z[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        x = np.cross(z, tmp)
        x /= np.linalg.norm(x)

    y = np.cross(z, x)
    y /= np.linalg.norm(y)
    return x, y, z


def _azimuths(vecs, x, y, z):
    vp = vecs - (vecs @ z)[:, np.newaxis] * z
    return np.degrees(np.arctan2(vp @ y, vp @ x))


def get_twist_angle(coord9):
    x, y, z = get_c4_frame(coord9)
    phi_bot = np.sort(_azimuths(coord9[BOTTOM], x, y, z))
    phi_top = np.sort(_azimuths(coord9[TOP], x, y, z))
    offsets = (phi_top - phi_bot + 90.0) % 180.0 - 90.0
    return float(offsets.mean())


def build_local_ideal_directions(coord9):
    x, y, z = get_c4_frame(coord9)

    zh = coord9 @ z
    vp = coord9 - zh[:, np.newaxis] * z
    radii = np.linalg.norm(vp, axis=1)

    r_bot = float(radii[BOTTOM].mean())
    z_bot = float(zh[BOTTOM].mean())
    r_top = float(radii[TOP].mean())
    z_top = float(zh[TOP].mean())
    r_cap = float(radii[CAP[0]])
    z_cap = float(zh[CAP[0]])

    def make_dirs(twist_deg):
        out = np.zeros((9, 3))
        phi_b = np.radians(np.arange(4) * 90.0)
        phi_t = phi_b + np.radians(twist_deg)

        out[BOTTOM] = (
            r_bot * np.cos(phi_b)[:, np.newaxis] * x[np.newaxis, :]
            + r_bot * np.sin(phi_b)[:, np.newaxis] * y[np.newaxis, :]
            + z_bot * z[np.newaxis, :]
        )
        out[TOP] = (
            r_top * np.cos(phi_t)[:, np.newaxis] * x[np.newaxis, :]
            + r_top * np.sin(phi_t)[:, np.newaxis] * y[np.newaxis, :]
            + z_top * z[np.newaxis, :]
        )
        out[CAP[0]] = r_cap * x + z_cap * z

        norms = np.linalg.norm(out, axis=1, keepdims=True)
        norms = np.where(norms > 1e-12, norms, 1.0)
        return out / norms

    return make_dirs(SAP_TWIST_DEG), make_dirs(TSAP_TWIST_DEG)


CYCLIC_PERMS = []
for db in range(4):
    for dt in range(4):
        p = list(range(9))
        for ii, orig in enumerate(BOTTOM):
            p[orig] = BOTTOM[(ii + db) % 4]
        for ii, orig in enumerate(TOP):
            p[orig] = TOP[(ii + dt) % 4]
        CYCLIC_PERMS.append(p)
CYCLIC_PERMS = np.array(CYCLIC_PERMS, dtype=int)


def min_rmsd_cyclic(coord9, dirs9, return_transform=False):
    real_r = np.linalg.norm(coord9, axis=1)
    q_unit = coord9 / np.where(real_r > 1e-12, real_r, 1.0)[:, np.newaxis]

    ps_unit = dirs9[CYCLIC_PERMS]
    _, rs = _kabsch_batch(ps_unit, q_unit)

    rotated_unit = np.einsum("kni,kji->knj", ps_unit, rs)
    ideal_placed = rotated_unit * real_r[np.newaxis, :, np.newaxis]

    diff = ideal_placed - coord9[np.newaxis]
    rmsds = np.sqrt(np.mean(np.sum(diff * diff, axis=2), axis=1))

    best_k = int(np.argmin(rmsds))
    best_rmsd = float(rmsds[best_k])

    if return_transform:
        return best_rmsd, ideal_placed[best_k]
    return best_rmsd


def classify_geom(ring_tors, chrom_tor, thresh=CLASSIFY_THRESH):
    ring_arr = np.asarray(ring_tors, dtype=float)
    valid = ring_arr[~np.isnan(ring_arr)]
    if len(valid) == 0 or np.isnan(chrom_tor):
        return "UNK"
    mean_ring = float(valid.mean())
    if abs(mean_ring) < thresh or abs(chrom_tor) < thresh:
        return "UNK"
    return "SAP" if np.sign(mean_ring) != np.sign(chrom_tor) else "TSAP"

# =============================================================================
# Tc inversion helper (for optional --invert-tc input generation)
# =============================================================================


def invert_tc_gro(xp):
    xp = xp.copy()

    i_n4 = TC_N4_IDX - 1
    i_c17 = TC_C17_IDX - 1
    i_c24 = TC_C24_IDX - 1
    i_n8 = TC_N8_IDX - 1
    i_h45 = TC_H45_IDX - 1
    i_h46 = TC_H46_IDX - 1

    p_n4 = xp[i_n4].copy()
    p_c24 = xp[i_c24].copy()
    p_n8 = xp[i_n8].copy()

    plane_n = np.cross(p_c24 - p_n4, p_n8 - p_n4)
    pn = np.linalg.norm(plane_n)
    if pn < 1e-9:
        sys.exit("ERROR: N4, C24, N8 are collinear - cannot define reflection plane.")
    plane_n /= pn

    for idx in (i_c17, i_h45, i_h46):
        rel = xp[idx] - p_n4
        xp[idx] = xp[idx] - 2.0 * np.dot(rel, plane_n) * plane_n

    return xp

# =============================================================================
# A2: pure geometry extended score
# =============================================================================


def cshm_score(real_xyz, ideal_xyz):
    diff2 = np.sum((real_xyz - ideal_xyz) ** 2)
    cen = real_xyz.mean(axis=0)
    denom = np.sum((real_xyz - cen) ** 2)
    if denom < 1e-12:
        return 0.0
    return float(100.0 * diff2 / denom)


def classify_a2(a2_sap, a2_tsap, ambig=A2_AMBIG_THRESH_A):
    d = a2_tsap - a2_sap
    if abs(d) < ambig:
        return "AMB"
    return "SAP" if d > 0.0 else "TSAP"


def make_a2_reference(xp_nm):
    eu = xp_nm[METAL_GRO - 1]
    ref_coord9_A = (xp_nm[[g - 1 for g in COORD_GRO]] - eu) * 10.0
    ref_ext_A = (xp_nm[[g - 1 for g in A2_EXT_GRO]] - eu) * 10.0
    return {"coord9_A": ref_coord9_A, "ext_A": ref_ext_A}


def compute_a2_scores(coord9_A, ideal_sap, ideal_tsap, ext_obs_A, ref_a2):
    def eval_class(ideal9):
        s, R = procrustes_scale_rotate(ref_a2["coord9_A"], ideal9)
        ext_pred = s * (ref_a2["ext_A"] @ R.T)

        real_ext = np.vstack([coord9_A, ext_obs_A])
        ideal_ext = np.vstack([ideal9, ext_pred])

        a2 = float(np.sqrt(np.mean(np.sum((real_ext - ideal_ext) ** 2, axis=1))))
        cshm = cshm_score(real_ext, ideal_ext)
        return a2, cshm

    a2_sap, cshm_sap = eval_class(ideal_sap)
    a2_tsap, cshm_tsap = eval_class(ideal_tsap)

    return {
        "a2_sap": a2_sap,
        "a2_tsap": a2_tsap,
        "delta_a2": a2_tsap - a2_sap,
        "cshm_sap": cshm_sap,
        "cshm_tsap": cshm_tsap,
        "geom_a2": classify_a2(a2_sap, a2_tsap),
    }

# =============================================================================
# Metric extraction
# =============================================================================


def extract_geometry(xp_nm, ref_a2):
    eu_nm = xp_nm[METAL_GRO - 1]
    coord9_nm = xp_nm[[g - 1 for g in COORD_GRO]] - eu_nm

    coord9_A = coord9_nm * 10.0
    eu_A = eu_nm * 10.0
    ext_obs_A = (xp_nm[[g - 1 for g in A2_EXT_GRO]] - eu_nm) * 10.0

    twist = get_twist_angle(coord9_A)
    dirs_sap, dirs_tsap = build_local_ideal_directions(coord9_A)
    rmsd_sap, ideal_sap = min_rmsd_cyclic(coord9_A, dirs_sap, return_transform=True)
    rmsd_tsap, ideal_tsap = min_rmsd_cyclic(coord9_A, dirs_tsap, return_transform=True)

    ring_tors = []
    for _, i, j, k, l in RING_TORS:
        ring_tors.append(dihedral_deg(xp_nm[i - 1], xp_nm[j - 1], xp_nm[k - 1], xp_nm[l - 1]))
    _, i, j, k, l = CHROM_TOR
    tc = dihedral_deg(xp_nm[i - 1], xp_nm[j - 1], xp_nm[k - 1], xp_nm[l - 1])

    geom_torsion = classify_geom(ring_tors, tc)
    a2 = compute_a2_scores(coord9_A, ideal_sap, ideal_tsap, ext_obs_A, ref_a2)

    return {
        "eu_pos": eu_A,
        "coord9": coord9_A,
        "twist": twist,
        "rmsd_sap": float(rmsd_sap),
        "rmsd_tsap": float(rmsd_tsap),
        "ideal_sap": ideal_sap,
        "ideal_tsap": ideal_tsap,
        "ring_tors": ring_tors,
        "chrom_tor": tc,
        "geom_torsion": geom_torsion,
        **a2,
    }

# =============================================================================
# Output
# =============================================================================


def write_pdb(atoms, xp_nm, geo, outfile, label):
    if geo["a2_sap"] <= geo["a2_tsap"]:
        ideal = geo["ideal_sap"]
        ideal_label = "SAP"
    else:
        ideal = geo["ideal_tsap"]
        ideal_label = "TSAP"

    abs_ideal = geo["eu_pos"] + ideal
    xp_A = xp_nm * 10.0

    with open(outfile, "w") as f:
        f.write(f"REMARK  label={label}\n")
        f.write(
            f"REMARK  torsion_geom={geo['geom_torsion']}  a2_geom={geo['geom_a2']}  "
            f"A_SAP={geo['rmsd_sap']:.3f}A  A_TSAP={geo['rmsd_tsap']:.3f}A  "
            f"A2_SAP={geo['a2_sap']:.3f}A  A2_TSAP={geo['a2_tsap']:.3f}A\n"
        )
        f.write(f"REMARK  Chain A = complex  |  Chain B = ideal {ideal_label} coordination geometry\n")

        for i, atom in enumerate(atoms):
            p = xp_A[i]
            name = atom["atomname"][:4].ljust(4)
            f.write(
                f"ATOM  {i+1:5d} {name} {atom['resname']:<3s} A{1:4d}    "
                f"{p[0]:8.3f}{p[1]:8.3f}{p[2]:8.3f}  1.00  0.00\n"
            )

        for j, (dname, dp) in enumerate(zip(DUM_NAMES, abs_ideal)):
            serial = len(atoms) + j + 1
            f.write(
                f"HETATM{serial:5d} {dname} DUM B{2:4d}    "
                f"{dp[0]:8.3f}{dp[1]:8.3f}{dp[2]:8.3f}  1.00  0.00\n"
            )

        f.write("END\n")

    print(f"  Wrote: {outfile}")


def _geo_block(label, geo):
    lines = []
    lines.append(f"  +-- {label}")
    lines.append(f"  |  Torsion classification       : {geo['geom_torsion']}")
    lines.append(f"  |  A2 classification            : {geo['geom_a2']}")
    lines.append(f"  |  Twist angle (TOP-BOTTOM)     : {geo['twist']:+.2f} deg")
    lines.append("  |")
    lines.append("  |  Part A (coordination-only):")
    lines.append(f"  |    RMSD to ideal SAP          = {geo['rmsd_sap']:.4f} A")
    lines.append(f"  |    RMSD to ideal TSAP         = {geo['rmsd_tsap']:.4f} A")
    lines.append("  |")
    lines.append("  |  Part A2 (pure geometry, extended):")
    lines.append(f"  |    A2_SAP (RMSD)              = {geo['a2_sap']:.4f} A")
    lines.append(f"  |    A2_TSAP (RMSD)             = {geo['a2_tsap']:.4f} A")
    lines.append(f"  |    deltaA2 (TSAP-SAP)         = {geo['delta_a2']:+.4f} A")
    lines.append(f"  |    CShM_SAP                   = {geo['cshm_sap']:.4f}")
    lines.append(f"  |    CShM_TSAP                  = {geo['cshm_tsap']:.4f}")
    lines.append("  |")
    lines.append("  |  Part B torsions:")

    mean_ring = float(np.nanmean(geo["ring_tors"]))
    for (name, *_), ang in zip(RING_TORS, geo["ring_tors"]):
        lines.append(f"  |    {name.strip():<22s}: {ang:+8.2f} deg")
    lines.append(f"  |    {'mean ring':<22s}: {mean_ring:+8.2f} deg")
    lines.append(f"  |    {CHROM_TOR[0].strip():<22s}: {geo['chrom_tor']:+8.2f} deg")
    lines.append("  +--------------------------------")
    return lines


def write_summary(geo_orig, geo_inv, stem_orig, stem_inv, outfile):
    sep = "=" * 84
    out = []

    out.append(sep)
    out.append("  ana_geometry_static.py - geometry report (A, A2-pure-geometry, B)")
    out.append(sep)
    out.append(f"  Input (original) : {stem_orig}")
    if stem_inv:
        out.append(f"  Input (inverted) : {stem_inv}")
    out.append("")

    out.append("  ORIGINAL geometry:")
    out.extend(_geo_block("original", geo_orig))
    out.append("")

    if geo_inv is not None:
        out.append("  Tc-INVERTED geometry:")
        out.extend(_geo_block("Tc-inverted", geo_inv))
        out.append("")

        out.append(f"  {'Quantity':<36s}  {'Original':>10s}  {'Inverted':>10s}  {'Delta':>10s}")
        out.append("  " + "-" * 80)

        def row(label, vo, vi, fmt="{:+8.2f}"):
            return (
                f"  {label:<36s}  {fmt.format(vo):>10s}  {fmt.format(vi):>10s}  "
                f"{fmt.format(vi - vo):>10s}"
            )

        out.append(row("Twist angle (deg)", geo_orig["twist"], geo_inv["twist"]))
        out.append(row("A RMSD to SAP (A)", geo_orig["rmsd_sap"], geo_inv["rmsd_sap"], "{:8.4f}"))
        out.append(row("A RMSD to TSAP (A)", geo_orig["rmsd_tsap"], geo_inv["rmsd_tsap"], "{:8.4f}"))
        out.append(row("A2_SAP (A)", geo_orig["a2_sap"], geo_inv["a2_sap"], "{:8.4f}"))
        out.append(row("A2_TSAP (A)", geo_orig["a2_tsap"], geo_inv["a2_tsap"], "{:8.4f}"))
        out.append(row("deltaA2 (A)", geo_orig["delta_a2"], geo_inv["delta_a2"], "{:+8.4f}"))
        out.append(row("CShM_SAP", geo_orig["cshm_sap"], geo_inv["cshm_sap"], "{:8.4f}"))
        out.append(row("CShM_TSAP", geo_orig["cshm_tsap"], geo_inv["cshm_tsap"], "{:8.4f}"))

        for (name, *_), ao, ai in zip(RING_TORS, geo_orig["ring_tors"], geo_inv["ring_tors"]):
            out.append(row(name.strip(), ao, ai))

        out.append(
            row(
                "mean ring torsion (deg)",
                float(np.nanmean(geo_orig["ring_tors"])),
                float(np.nanmean(geo_inv["ring_tors"])),
            )
        )
        out.append(row(CHROM_TOR[0].strip(), geo_orig["chrom_tor"], geo_inv["chrom_tor"]))

        out.append("  " + "-" * 80)
        out.append(f"  Torsion class: {geo_orig['geom_torsion']} -> {geo_inv['geom_torsion']}")
        out.append(f"  A2 class     : {geo_orig['geom_a2']} -> {geo_inv['geom_a2']}")

    out.append("")
    out.append(sep)

    text = "\n".join(out) + "\n"
    with open(outfile, "w") as fh:
        fh.write(text)

    print(f"  Wrote: {outfile}")
    print()
    print(text)

# =============================================================================
# CLI
# =============================================================================


def parse_args():
    p = argparse.ArgumentParser(description="Static single-frame geometry analysis (A, A2, B)")
    p.add_argument("--gro", required=True, metavar="FILE", help="Original GRO file")
    p.add_argument("--gro-inv", default=None, metavar="FILE", help="Pre-inverted GRO file")
    p.add_argument("--invert-tc", action="store_true", help="Generate Tc-inverted coordinates in memory")
    p.add_argument("--out-dir", default=None, metavar="DIR", help="Output directory")
    return p.parse_args()


def main():
    args = parse_args()

    if not os.path.isfile(args.gro):
        sys.exit(f"ERROR: GRO file not found: {args.gro}")

    out_dir = args.out_dir or os.path.dirname(os.path.abspath(args.gro))
    os.makedirs(out_dir, exist_ok=True)

    stem = os.path.splitext(os.path.basename(args.gro))[0]

    print(f"\nLoading: {args.gro}")
    _, atoms, _ = read_gro(args.gro)
    xp_orig = atoms_to_xp(atoms)
    print(f"  Atoms: {len(atoms)}")

    # A2 reference is fixed from ORIGINAL structure for this run
    ref_a2 = make_a2_reference(xp_orig)

    print("  Analyzing original geometry ...")
    geo_orig = extract_geometry(xp_orig, ref_a2)
    write_pdb(atoms, xp_orig, geo_orig, os.path.join(out_dir, f"{stem}_geo_orig.pdb"), f"{stem}_original")

    geo_inv = None
    stem_inv = None
    atoms_inv = atoms

    if args.gro_inv:
        if not os.path.isfile(args.gro_inv):
            sys.exit(f"ERROR: Inverted GRO file not found: {args.gro_inv}")
        print(f"\nLoading inverted GRO: {args.gro_inv}")
        _, atoms_inv, _ = read_gro(args.gro_inv)
        if len(atoms_inv) != len(atoms):
            sys.exit("ERROR: Atom count mismatch between original and inverted GRO files.")
        xp_inv = atoms_to_xp(atoms_inv)
        stem_inv = args.gro_inv
    elif args.invert_tc:
        print("\nGenerating Tc-inverted coordinates in memory ...")
        xp_inv = invert_tc_gro(xp_orig)
        atoms_inv = [dict(a) for a in atoms]
        stem_inv = f"{stem} (Tc-inverted in memory)"

    if stem_inv is not None:
        print("  Analyzing inverted geometry ...")
        geo_inv = extract_geometry(xp_inv, ref_a2)
        write_pdb(
            atoms_inv,
            xp_inv,
            geo_inv,
            os.path.join(out_dir, f"{stem}_geo_inv.pdb"),
            f"{stem}_tc_inverted",
        )

    write_summary(
        geo_orig,
        geo_inv,
        args.gro,
        stem_inv,
        os.path.join(out_dir, f"{stem}_geo_summary.txt"),
    )

    print("Done.")


if __name__ == "__main__":
    main()
