#!/usr/bin/env python3
"""
metal_geo_analysis_a2.py
------------------------
Trajectory analysis for 9-coordinate Eu complexes.

Part A:
  Chimera-style coordination-sphere RMSD to ideal SAP/TSAP.

Part A2:
  Purely geometry-based extended score (11 points):
    - 9 coordination atoms
    - + 2 Tc-link atoms (C16, C23)
  The 2 extra ideal points are generated by class-specific Procrustes mapping
  from a fixed reference structure, without torsion sign rules and without
  additive penalties.

Part B:
  Torsion analysis (T1-T4 and Tc) with sign-based classification.
"""

import argparse
import csv
import os
import textwrap
import warnings

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import MDAnalysis as mda
import numpy as np

warnings.filterwarnings("ignore")

# =============================================================================
# Configuration (0-based MOL indices)
# =============================================================================

METAL_IDX = 54
COORD_IDX = [0, 1, 2, 3, 4, 5, 6, 7, 63]
BOTTOM = [3, 4, 5, 6]
TOP = [0, 1, 2, 7]
CAP = [8]

RING_TORS = [
    ("T1 N3-C8-C9-N4", 3, 8, 9, 4),
    ("T2 N4-C10-C11-N5", 4, 10, 11, 5),
    ("T3 N5-C12-C13-N6", 5, 12, 13, 6),
    ("T4 N6-C14-C15-N3", 6, 14, 15, 3),
]
CHROM_TOR = ("Tc N3-C16-C23-N7", 3, 16, 23, 7)

SAP_TWIST_DEG = -45.0
TSAP_TWIST_DEG = 0.0
CLASSIFY_THRESH = 10.0
A2_AMBIG_THRESH_A = 0.05

A2_EXT_IDX = [16, 23]  # C16, C23

C_SAP = "steelblue"
C_TSAP = "mediumorchid"
C_UNK = "lightgray"
TOR_COLS = ["#00b4d8", "#0077b6", "#48cae4", "#7b2d8b", "#c77dff"]

# =============================================================================
# Geometry helpers
# =============================================================================


def calc_dihedral(pos, i, j, k, l):
    b1 = pos[j] - pos[i]
    b2 = pos[k] - pos[j]
    b3 = pos[l] - pos[k]
    n1 = np.cross(b1, b2)
    n2 = np.cross(b2, b3)
    nn1 = np.linalg.norm(n1)
    nn2 = np.linalg.norm(n2)
    if nn1 < 1e-9 or nn2 < 1e-9:
        return np.nan
    n1 /= nn1
    n2 /= nn2
    b2n = b2 / np.linalg.norm(b2)
    return float(np.degrees(np.arctan2(np.dot(np.cross(n1, n2), b2n), np.dot(n1, n2))))


def calc_dihedrals_batch(pos, ijkl):
    i, j, k, l = ijkl[:, 0], ijkl[:, 1], ijkl[:, 2], ijkl[:, 3]
    b1 = pos[j] - pos[i]
    b2 = pos[k] - pos[j]
    b3 = pos[l] - pos[k]

    n1 = np.cross(b1, b2)
    n2 = np.cross(b2, b3)
    nn1 = np.linalg.norm(n1, axis=1, keepdims=True)
    nn2 = np.linalg.norm(n2, axis=1, keepdims=True)
    b2n = b2 / np.linalg.norm(b2, axis=1, keepdims=True)

    valid = (nn1[:, 0] > 1e-9) & (nn2[:, 0] > 1e-9)
    nn1 = np.where(nn1 > 1e-9, nn1, 1.0)
    nn2 = np.where(nn2 > 1e-9, nn2, 1.0)
    n1 /= nn1
    n2 /= nn2

    sin_term = np.einsum("ti,ti->t", np.cross(n1, n2), b2n)
    cos_term = np.einsum("ti,ti->t", n1, n2)
    out = np.degrees(np.arctan2(sin_term, cos_term))
    out[~valid] = np.nan
    return out


def kabsch(P, Q):
    H = P.T @ Q
    U, _, Vt = np.linalg.svd(H)
    d = float(np.sign(np.linalg.det(Vt.T @ U.T)))
    R = Vt.T @ np.diag([1.0, 1.0, d]) @ U.T
    diff = P @ R.T - Q
    rmsd = float(np.sqrt(np.mean(np.einsum("ij,ij->i", diff, diff))))
    return rmsd, R


def procrustes_scale_rotate(source, target):
    _, R = kabsch(source, target)
    src_rot = source @ R.T
    denom = float(np.sum(src_rot * src_rot))
    s = float(np.sum(src_rot * target) / denom) if denom > 1e-12 else 1.0
    return s, R


def _kabsch_batch(Ps, Q):
    H = np.einsum("kni,nj->kij", Ps, Q)
    U, _, Vt = np.linalg.svd(H)

    dets = np.linalg.det(np.einsum("kij,kjl->kil", Vt.swapaxes(1, 2), U.swapaxes(1, 2)))
    signs = np.sign(dets)

    diag = np.zeros((len(Ps), 3, 3))
    diag[:, 0, 0] = 1.0
    diag[:, 1, 1] = 1.0
    diag[:, 2, 2] = signs

    Rs = np.einsum("kij,kjl,klm->kim", Vt.swapaxes(1, 2), diag, U.swapaxes(1, 2))
    rotated = np.einsum("kni,kji->knj", Ps, Rs)
    diff = rotated - Q[np.newaxis]
    rmsds = np.sqrt(np.mean(np.sum(diff * diff, axis=2), axis=1))
    return rmsds, Rs


def align_pos(mob_pos, ref_pos, mask):
    mob_h = mob_pos[mask]
    ref_h = ref_pos[mask]
    cm = mob_h.mean(0)
    cr = ref_h.mean(0)
    _, R = kabsch(mob_h - cm, ref_h - cr)
    return (mob_pos - cm) @ R.T + cr


def get_c4_frame(coord9):
    ring_n = coord9[BOTTOM]
    centroid = ring_n.mean(0)
    _, _, Vt = np.linalg.svd(ring_n - centroid)
    z = Vt[-1]
    if np.dot(z, coord9[CAP[0]]) < 0:
        z = -z

    cap_vec = coord9[CAP[0]]
    cap_proj = cap_vec - np.dot(cap_vec, z) * z
    cap_norm = np.linalg.norm(cap_proj)
    if cap_norm > 1e-8:
        x = cap_proj / cap_norm
    else:
        tmp = np.array([1.0, 0.0, 0.0]) if abs(z[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        x = np.cross(z, tmp)
        x /= np.linalg.norm(x)
    y = np.cross(z, x)
    y /= np.linalg.norm(y)
    return x, y, z


def _azimuths(vecs, x, y, z):
    vp = vecs - (vecs @ z)[:, np.newaxis] * z
    return np.degrees(np.arctan2(vp @ y, vp @ x))


def get_twist_angle(coord9):
    x, y, z = get_c4_frame(coord9)
    phi_bot = np.sort(_azimuths(coord9[BOTTOM], x, y, z))
    phi_top = np.sort(_azimuths(coord9[TOP], x, y, z))
    offsets = (phi_top - phi_bot + 90.0) % 180.0 - 90.0
    return float(offsets.mean())


def build_local_ideal_directions(coord9):
    x, y, z = get_c4_frame(coord9)
    zh = coord9 @ z
    vp = coord9 - zh[:, np.newaxis] * z
    radii = np.linalg.norm(vp, axis=1)

    r_bot = float(radii[BOTTOM].mean())
    z_bot = float(zh[BOTTOM].mean())
    r_top = float(radii[TOP].mean())
    z_top = float(zh[TOP].mean())
    r_cap = float(radii[CAP[0]])
    z_cap = float(zh[CAP[0]])

    def make_dirs(twist_deg):
        out = np.zeros((9, 3))
        phi_b = np.radians(np.arange(4) * 90.0)
        phi_t = phi_b + np.radians(twist_deg)

        out[BOTTOM] = (
            r_bot * np.cos(phi_b)[:, np.newaxis] * x[np.newaxis, :]
            + r_bot * np.sin(phi_b)[:, np.newaxis] * y[np.newaxis, :]
            + z_bot * z[np.newaxis, :]
        )
        out[TOP] = (
            r_top * np.cos(phi_t)[:, np.newaxis] * x[np.newaxis, :]
            + r_top * np.sin(phi_t)[:, np.newaxis] * y[np.newaxis, :]
            + z_top * z[np.newaxis, :]
        )
        out[CAP[0]] = r_cap * x + z_cap * z

        norms = np.linalg.norm(out, axis=1, keepdims=True)
        norms = np.where(norms > 1e-12, norms, 1.0)
        return out / norms

    return make_dirs(SAP_TWIST_DEG), make_dirs(TSAP_TWIST_DEG)


_CYCLIC_PERMS = []
for _db in range(4):
    for _dt in range(4):
        _p = list(range(9))
        for _ii, _orig in enumerate(BOTTOM):
            _p[_orig] = BOTTOM[(_ii + _db) % 4]
        for _ii, _orig in enumerate(TOP):
            _p[_orig] = TOP[(_ii + _dt) % 4]
        _CYCLIC_PERMS.append(_p)
_CYCLIC_PERMS = np.array(_CYCLIC_PERMS, dtype=int)


def min_rmsd_cyclic(coord9, dirs9, return_transform=False):
    real_r = np.linalg.norm(coord9, axis=1)
    q_unit = coord9 / np.where(real_r > 1e-12, real_r, 1.0)[:, np.newaxis]

    ps_unit = dirs9[_CYCLIC_PERMS]
    _, Rs = _kabsch_batch(ps_unit, q_unit)
    rotated_unit = np.einsum("kni,kji->knj", ps_unit, Rs)
    ideal_placed = rotated_unit * real_r[np.newaxis, :, np.newaxis]

    diff = ideal_placed - coord9[np.newaxis]
    rmsds = np.sqrt(np.mean(np.sum(diff * diff, axis=2), axis=1))
    best_k = int(np.argmin(rmsds))
    best_rmsd = float(rmsds[best_k])

    if return_transform:
        return best_rmsd, ideal_placed[best_k]
    return best_rmsd


def classify_geom(ring_tors, chrom_tor, thresh=CLASSIFY_THRESH):
    ring_arr = np.asarray(ring_tors, dtype=float)
    valid = ring_arr[~np.isnan(ring_arr)]
    if len(valid) == 0 or np.isnan(chrom_tor):
        return "UNK"
    mean_ring = float(valid.mean())
    if abs(mean_ring) < thresh or abs(chrom_tor) < thresh:
        return "UNK"
    return "SAP" if np.sign(mean_ring) != np.sign(chrom_tor) else "TSAP"

# =============================================================================
# A2 pure geometry
# =============================================================================


def cshm_score(real_xyz, ideal_xyz):
    diff2 = np.sum((real_xyz - ideal_xyz) ** 2)
    cen = real_xyz.mean(axis=0)
    denom = np.sum((real_xyz - cen) ** 2)
    if denom < 1e-12:
        return 0.0
    return float(100.0 * diff2 / denom)


def classify_a2(a2_sap, a2_tsap, ambig=A2_AMBIG_THRESH_A):
    d = a2_tsap - a2_sap
    if abs(d) < ambig:
        return "AMB"
    return "SAP" if d > 0.0 else "TSAP"


def make_a2_reference(pos_ref):
    eu = pos_ref[METAL_IDX]
    coord9_ref = pos_ref[COORD_IDX] - eu
    ext_ref = pos_ref[A2_EXT_IDX] - eu
    return {"coord9": coord9_ref, "ext": ext_ref}


def compute_a2(coord9, ideal_sap, ideal_tsap, ext_obs, ref_a2):
    def eval_class(ideal9):
        s, R = procrustes_scale_rotate(ref_a2["coord9"], ideal9)
        ext_pred = s * (ref_a2["ext"] @ R.T)

        real_ext = np.vstack([coord9, ext_obs])
        ideal_ext = np.vstack([ideal9, ext_pred])

        a2 = float(np.sqrt(np.mean(np.sum((real_ext - ideal_ext) ** 2, axis=1))))
        cshm = cshm_score(real_ext, ideal_ext)
        return a2, cshm

    a2_sap, cshm_sap = eval_class(ideal_sap)
    a2_tsap, cshm_tsap = eval_class(ideal_tsap)

    return {
        "a2_sap": a2_sap,
        "a2_tsap": a2_tsap,
        "delta_a2": a2_tsap - a2_sap,
        "cshm_sap": cshm_sap,
        "cshm_tsap": cshm_tsap,
        "geom_a2": classify_a2(a2_sap, a2_tsap),
    }

# =============================================================================
# Trajectory loading
# =============================================================================


def load_mol_universe(tpr, xtc):
    import MDAnalysis.coordinates.XTC as XTC

    xtc_natoms = XTC.XTCReader(xtc).n_atoms
    u_tpr = mda.Universe(tpr)
    mol_tpr = u_tpr.select_atoms("resname MOL")
    n_mol = mol_tpr.n_atoms

    if xtc_natoms == n_mol:
        u = mda.Merge(mol_tpr)
        u.load_new(xtc)
        mol_ag = u.atoms
    elif xtc_natoms == u_tpr.atoms.n_atoms:
        u = mda.Universe(tpr, xtc)
        mol_ag = u.select_atoms("resname MOL")
    else:
        raise ValueError(
            f"XTC has {xtc_natoms} atoms; TPR has {u_tpr.atoms.n_atoms} total and {n_mol} MOL atoms"
        )

    return u, mol_ag


def heavy_mask(mol_ag):
    return mol_ag.masses > 1.5


def make_mol_whole(u, mol_ag=None):
    try:
        ts = u.trajectory.ts
        if ts.dimensions is not None and ts.dimensions[0] > 0:
            ag = mol_ag if mol_ag is not None else u.atoms
            ag.unwrap(compound="residues")
    except Exception:
        pass

# =============================================================================
# Data collection
# =============================================================================


_TORSION_IJKL = np.array(
    [[i, j, k, l] for _, i, j, k, l in RING_TORS] + [[CHROM_TOR[1], CHROM_TOR[2], CHROM_TOR[3], CHROM_TOR[4]]],
    dtype=int,
)


def collect_trajectory_data(u, mol_ag, ref_pos, hmask, ref_a2):
    records = []

    for ts in u.trajectory:
        make_mol_whole(u, mol_ag)
        raw_pos = mol_ag.positions.copy()
        aln_pos = align_pos(raw_pos, ref_pos, hmask)

        eu = aln_pos[METAL_IDX]
        coord = aln_pos[COORD_IDX] - eu
        ext_obs = aln_pos[A2_EXT_IDX] - eu

        dirs_sap, dirs_tsap = build_local_ideal_directions(coord)
        rmsd_sap, ideal_sap = min_rmsd_cyclic(coord, dirs_sap, return_transform=True)
        rmsd_tsap, ideal_tsap = min_rmsd_cyclic(coord, dirs_tsap, return_transform=True)

        tors = calc_dihedrals_batch(raw_pos, _TORSION_IJKL)
        ring_t = list(tors[:4])
        tc = float(tors[4])
        geom_torsion = classify_geom(ring_t, tc)

        a2 = compute_a2(coord, ideal_sap, ideal_tsap, ext_obs, ref_a2)

        records.append(
            {
                "frame": int(ts.frame),
                "time": float(ts.time),
                "pos": aln_pos.copy(),
                "coord9": coord.copy(),
                "eu": eu.copy(),
                "rmsd_sap": float(rmsd_sap),
                "rmsd_tsap": float(rmsd_tsap),
                "ideal_sap": ideal_sap,
                "ideal_tsap": ideal_tsap,
                "ring_tors": ring_t,
                "chrom_tor": tc,
                "geom_torsion": geom_torsion,
                **a2,
            }
        )

    return records

# =============================================================================
# Output
# =============================================================================


def write_pdb_with_dummies(mol_atoms, pos, ideal_placed, eu_pos, outfile, frame_idx, label):
    def elem_symbol(atype):
        t = atype.lower()
        if t.startswith("eu") or t.startswith("e"):
            return "Eu"
        if t.startswith("c"):
            return "C"
        if t.startswith("n"):
            return "N"
        if t.startswith("o"):
            return "O"
        if t.startswith("h"):
            return "H"
        return atype[:1].upper()

    with open(outfile, "w") as f:
        f.write(f"REMARK  frame={frame_idx}  label={label}\n")
        f.write("REMARK  Chain A = complex  |  Chain B = ideal coordination polyhedron\n")

        for i, atom in enumerate(mol_atoms):
            p = pos[i]
            name = atom.name[:4].ljust(4)
            elem = elem_symbol(atom.type)
            f.write(
                f"ATOM  {i+1:5d} {name} {atom.resname:<3s} A{1:4d}    "
                f"{p[0]:8.3f}{p[1]:8.3f}{p[2]:8.3f}  1.00  0.00"
                f"          {elem:>2s}\n"
            )

        abs_ideal = eu_pos + ideal_placed
        dnames = ["DO0 ", "DO1 ", "DO2 ", "DN3 ", "DN4 ", "DN5 ", "DN6 ", "DN7 ", "DN63"]
        for j, (dname, dp) in enumerate(zip(dnames, abs_ideal)):
            serial = len(mol_atoms) + j + 1
            f.write(
                f"HETATM{serial:5d} {dname} DUM B{2:4d}    "
                f"{dp[0]:8.3f}{dp[1]:8.3f}{dp[2]:8.3f}  1.00  0.00           X\n"
            )

        f.write("END\n")


def run_part_A_A2(records, mol_atoms, outdir, sysname):
    os.makedirs(outdir, exist_ok=True)

    times = np.array([r["time"] for r in records])
    a_sap = np.array([r["rmsd_sap"] for r in records])
    a_tsap = np.array([r["rmsd_tsap"] for r in records])
    a2_sap = np.array([r["a2_sap"] for r in records])
    a2_tsap = np.array([r["a2_tsap"] for r in records])
    da2 = np.array([r["delta_a2"] for r in records])
    cshm_sap = np.array([r["cshm_sap"] for r in records])
    cshm_tsap = np.array([r["cshm_tsap"] for r in records])

    csv_path = os.path.join(outdir, "A_A2_timeseries.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "frame", "time_ps", "A_SAP_A", "A_TSAP_A",
            "A2_SAP_A", "A2_TSAP_A", "deltaA2_A",
            "CShM_SAP", "CShM_TSAP", "A2_class",
        ])
        for r in records:
            w.writerow([
                r["frame"], f"{r['time']:.1f}",
                f"{r['rmsd_sap']:.4f}", f"{r['rmsd_tsap']:.4f}",
                f"{r['a2_sap']:.4f}", f"{r['a2_tsap']:.4f}", f"{r['delta_a2']:.4f}",
                f"{r['cshm_sap']:.4f}", f"{r['cshm_tsap']:.4f}", r["geom_a2"],
            ])

    tns = times / 1000.0
    fig, ax = plt.subplots(figsize=(10, 4.2))
    ax.plot(tns, a_sap, color=C_SAP, lw=1.3, alpha=0.85, label="A -> SAP")
    ax.plot(tns, a_tsap, color=C_TSAP, lw=1.3, alpha=0.85, label="A -> TSAP")
    ax.plot(tns, a2_sap, color=C_SAP, lw=1.1, ls="--", alpha=0.95, label="A2 -> SAP")
    ax.plot(tns, a2_tsap, color=C_TSAP, lw=1.1, ls="--", alpha=0.95, label="A2 -> TSAP")
    ax.set_xlabel("Time (ns)")
    ax.set_ylabel("RMSD / score (A)")
    ax.set_title(f"{sysname} - Part A and A2")
    ax.legend(framealpha=0.85, ncol=2)
    plt.tight_layout()
    fig.savefig(os.path.join(outdir, "A_A2_timeseries.png"), dpi=150)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 4.2))
    bins = 60
    cnt_as, edges = np.histogram(a_sap, bins=bins)
    ctr = 0.5 * (edges[:-1] + edges[1:])
    cnt_at, _ = np.histogram(a_tsap, bins=edges)
    cnt_a2s, _ = np.histogram(a2_sap, bins=edges)
    cnt_a2t, _ = np.histogram(a2_tsap, bins=edges)
    n = max(len(records), 1)

    ax.plot(ctr, cnt_as / n, color=C_SAP, lw=1.8, label="A -> SAP")
    ax.plot(ctr, cnt_at / n, color=C_TSAP, lw=1.8, label="A -> TSAP")
    ax.plot(ctr, cnt_a2s / n, color=C_SAP, lw=1.2, ls="--", label="A2 -> SAP")
    ax.plot(ctr, cnt_a2t / n, color=C_TSAP, lw=1.2, ls="--", label="A2 -> TSAP")
    ax.set_xlabel("RMSD / score (A)")
    ax.set_ylabel("Fraction of frames")
    ax.set_title(f"{sysname} - A/A2 distributions")
    ax.legend(framealpha=0.85, ncol=2)
    plt.tight_layout()
    fig.savefig(os.path.join(outdir, "A_A2_histogram.png"), dpi=150)
    plt.close(fig)

    fi_sap = int(np.argmin(a2_sap))
    fi_tsap = int(np.argmin(a2_tsap))

    rs = records[fi_sap]
    write_pdb_with_dummies(
        mol_atoms, rs["pos"], rs["ideal_sap"], rs["eu"],
        os.path.join(outdir, f"A2_rep_SAP_{fi_sap:04d}.pdb"), fi_sap,
        f"A2_min_SAP_frame{fi_sap}",
    )

    rt = records[fi_tsap]
    write_pdb_with_dummies(
        mol_atoms, rt["pos"], rt["ideal_tsap"], rt["eu"],
        os.path.join(outdir, f"A2_rep_TSAP_{fi_tsap:04d}.pdb"), fi_tsap,
        f"A2_min_TSAP_frame{fi_tsap}",
    )

    return {
        "times": times,
        "a_sap": a_sap,
        "a_tsap": a_tsap,
        "a2_sap": a2_sap,
        "a2_tsap": a2_tsap,
        "delta_a2": da2,
        "cshm_sap": cshm_sap,
        "cshm_tsap": cshm_tsap,
    }


def run_part_B(records, outdir, sysname):
    os.makedirs(outdir, exist_ok=True)

    times = np.array([r["time"] for r in records])
    tnames = [n for n, *_ in RING_TORS] + [CHROM_TOR[0]]
    tor_mat = np.array([r["ring_tors"] + [r["chrom_tor"]] for r in records]).T

    ts_csv = os.path.join(outdir, "B_torsions_timeseries.csv")
    with open(ts_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["frame", "time_ps"] + tnames + ["geom_torsion", "geom_a2"])
        for i, r in enumerate(records):
            vals = [f"{v:.2f}" for v in tor_mat[:, i]]
            w.writerow([r["frame"], f"{r['time']:.1f}"] + vals + [r["geom_torsion"], r["geom_a2"]])

    fig, ax = plt.subplots(figsize=(11, 4.5))
    for name, col, vals in zip(tnames, TOR_COLS, tor_mat):
        ax.plot(times / 1000.0, vals, color=col, lw=1.3, alpha=0.85, label=name)
    ax.axhline(0, color="k", lw=0.6, ls="--", alpha=0.5)
    ax.set_xlabel("Time (ns)")
    ax.set_ylabel("Torsion (deg)")
    ax.set_ylim(-185, 185)
    ax.set_yticks([-180, -90, 0, 90, 180])
    ax.legend(fontsize=8, ncol=len(tnames), framealpha=0.85)
    ax.set_title(f"{sysname} - Part B torsions")
    plt.tight_layout()
    fig.savefig(os.path.join(outdir, "B_torsions_timeseries.png"), dpi=150)
    plt.close(fig)

# =============================================================================
# Summary and CLI
# =============================================================================


def write_summary(records, a_stats, outdir, sysname):
    geoms_t = [r["geom_torsion"] for r in records]
    geoms_a2 = [r["geom_a2"] for r in records]
    nf = len(records)

    def frac(arr, label):
        n = arr.count(label)
        return n, (100.0 * n / nf if nf else 0.0)

    n_sap_t, p_sap_t = frac(geoms_t, "SAP")
    n_tsap_t, p_tsap_t = frac(geoms_t, "TSAP")
    n_unk_t, p_unk_t = frac(geoms_t, "UNK")

    n_sap_a2, p_sap_a2 = frac(geoms_a2, "SAP")
    n_tsap_a2, p_tsap_a2 = frac(geoms_a2, "TSAP")
    n_amb_a2, p_amb_a2 = frac(geoms_a2, "AMB")

    out = os.path.join(outdir, "SUMMARY_A2.txt")
    with open(out, "w") as f:
        f.write(f"System: {sysname}\n")
        f.write(f"Frames: {nf}\n\n")
        f.write("Part A (coordination-only)\n")
        f.write(f"  RMSD->SAP  mean +/- std: {a_stats['a_sap'].mean():.4f} +/- {a_stats['a_sap'].std():.4f} A\n")
        f.write(f"  RMSD->TSAP mean +/- std: {a_stats['a_tsap'].mean():.4f} +/- {a_stats['a_tsap'].std():.4f} A\n\n")

        f.write("Part A2 (pure geometry, extended set)\n")
        f.write(f"  A2->SAP    mean +/- std: {a_stats['a2_sap'].mean():.4f} +/- {a_stats['a2_sap'].std():.4f} A\n")
        f.write(f"  A2->TSAP   mean +/- std: {a_stats['a2_tsap'].mean():.4f} +/- {a_stats['a2_tsap'].std():.4f} A\n")
        f.write(f"  deltaA2    mean +/- std: {a_stats['delta_a2'].mean():+.4f} +/- {a_stats['delta_a2'].std():.4f} A\n")
        f.write(f"  CShM_SAP   mean +/- std: {a_stats['cshm_sap'].mean():.4f} +/- {a_stats['cshm_sap'].std():.4f}\n")
        f.write(f"  CShM_TSAP  mean +/- std: {a_stats['cshm_tsap'].mean():.4f} +/- {a_stats['cshm_tsap'].std():.4f}\n")
        f.write(
            f"  A2 class fractions: SAP={n_sap_a2} ({p_sap_a2:.1f}%), "
            f"TSAP={n_tsap_a2} ({p_tsap_a2:.1f}%), "
            f"AMB={n_amb_a2} ({p_amb_a2:.1f}%)\n\n"
        )

        f.write("Part B torsion class fractions\n")
        f.write(
            f"  SAP={n_sap_t} ({p_sap_t:.1f}%), "
            f"TSAP={n_tsap_t} ({p_tsap_t:.1f}%), "
            f"UNK={n_unk_t} ({p_unk_t:.1f}%)\n"
        )

    return out


def parse_args():
    p = argparse.ArgumentParser(
        description="Trajectory analysis with Part A, pure-geometry A2, and Part B",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """
            Example:
              python metal_geo_analysis_a2.py \\
                --system me_sssL_sap --tpr me_sssL_sap/pr_0.tpr --xtc me_sssL_sap/pr_0.xtc
            """
        ),
    )

    p.add_argument("--system", dest="names", action="append", metavar="NAME")
    p.add_argument("--tpr", dest="tprs", action="append", metavar="FILE")
    p.add_argument("--xtc", dest="xtcs", action="append", metavar="FILE")
    p.add_argument("--outdir", default="analysis_a2", metavar="DIR")

    args = p.parse_args()
    names = args.names or []
    tprs = args.tprs or []
    xtcs = args.xtcs or []

    if not names:
        p.error("No systems specified. Use repeated --system/--tpr/--xtc triplets.")
    if not (len(names) == len(tprs) == len(xtcs)):
        p.error("Mismatch among --system, --tpr, and --xtc counts.")

    systems = {}
    for n, tpr, xtc in zip(names, tprs, xtcs):
        if n in systems:
            p.error(f"Duplicate system name: {n}")
        if not os.path.isfile(tpr):
            p.error(f"TPR not found: {tpr}")
        if not os.path.isfile(xtc):
            p.error(f"XTC not found: {xtc}")
        systems[n] = {"tpr": tpr, "xtc": xtc, "outdir": os.path.join(n, args.outdir)}

    return systems


def main():
    systems = parse_args()

    for sysname, cfg in systems.items():
        print("\n" + "=" * 70)
        print(f"System: {sysname}")
        print("=" * 70)

        u, mol_ag = load_mol_universe(cfg["tpr"], cfg["xtc"])
        print(f"MOL atoms: {mol_ag.n_atoms}   Frames: {u.trajectory.n_frames}")

        u.trajectory[0]
        make_mol_whole(u, mol_ag)
        ref_pos = mol_ag.positions.copy()
        hmask = heavy_mask(mol_ag)
        ref_a2 = make_a2_reference(ref_pos)

        print("Collecting trajectory metrics ...")
        records = collect_trajectory_data(u, mol_ag, ref_pos, hmask, ref_a2)
        print(f"Collected {len(records)} frames")

        outdir = cfg["outdir"]
        os.makedirs(outdir, exist_ok=True)

        print("Writing Part A/A2 outputs ...")
        a_stats = run_part_A_A2(records, mol_ag, outdir, sysname)

        print("Writing Part B outputs ...")
        run_part_B(records, outdir, sysname)

        summary = write_summary(records, a_stats, outdir, sysname)

        geoms_t = [r["geom_torsion"] for r in records]
        geoms_a2 = [r["geom_a2"] for r in records]
        nf = len(records)

        def pct(n):
            return 100.0 * n / nf if nf else 0.0

        print("Summary:")
        print(
            f"  Torsion class: SAP={geoms_t.count('SAP')} ({pct(geoms_t.count('SAP')):.1f}%), "
            f"TSAP={geoms_t.count('TSAP')} ({pct(geoms_t.count('TSAP')):.1f}%), "
            f"UNK={geoms_t.count('UNK')} ({pct(geoms_t.count('UNK')):.1f}%)"
        )
        print(
            f"  A2 class     : SAP={geoms_a2.count('SAP')} ({pct(geoms_a2.count('SAP')):.1f}%), "
            f"TSAP={geoms_a2.count('TSAP')} ({pct(geoms_a2.count('TSAP')):.1f}%), "
            f"AMB={geoms_a2.count('AMB')} ({pct(geoms_a2.count('AMB')):.1f}%)"
        )
        print(f"  A  mean SAP/TSAP  : {a_stats['a_sap'].mean():.3f} / {a_stats['a_tsap'].mean():.3f} A")
        print(f"  A2 mean SAP/TSAP  : {a_stats['a2_sap'].mean():.3f} / {a_stats['a2_tsap'].mean():.3f} A")
        print(f"  Summary file: {summary}")

    print("\nAll done.")


if __name__ == "__main__":
    main()
