import sys
import numpy as np

class gro:

 def __init__(self,f_gro=None, pdb_obj=None, box=[10.0,10.0,10.0] ):

  if not f_gro is None:
   self.load_gro(f_gro)

  elif not pdb_obj is None:
   self.load_pdbobj(pdb_obj,box)

  else:
   print('Error! Failed to create gro object.')
   sys.exit()


 def load_pdbobj(self, pdb_obj, box):

  self.box = np.array(box, dtype= np.float64)
  

  _atoms = pdb_obj.atoms
  self.natom = len(_atoms)
  self.xp = np.zeros((self.natom, 3))
  self.resid = np.zeros(self.natom, dtype=np.int32)
  self.atomid = np.zeros(self.natom, dtype=np.int32)
  self.resnm = ['' for _i in range(self.natom)]
  self.atomnm = ['' for _i in range(self.natom)]
 
  for __i in range(self.natom):
   _ai = _atoms[__i]
   self.resid[__i] = _ai[4]
   self.resnm[__i] = _ai[2]
   self.atomnm[__i] = _ai[1]
   self.atomid[__i] = _ai[0]
   self.xp[__i,0] = _ai[5]*0.1
   self.xp[__i,1] = _ai[6]*0.1
   self.xp[__i,2] = _ai[7]*0.1



 def load_gro(self, fnm):

  _f = open(fnm,'r')
  _rl = _f.readline()
  _rl = _f.readline()
  self.natom = int(_rl[:-1])
  self.xp = np.zeros((self.natom, 3))
  self.resid = np.zeros(self.natom, dtype=np.int32)
  self.atomid = np.zeros(self.natom, dtype=np.int32)
  self.resnm = ['' for _i in range(self.natom)]
  self.atomnm = ['' for _i in range(self.natom)]
  for _i in range(self.natom):
   _rl  = _f.readline()[:-1]
   self.resid[_i] = int(_rl[0:5])
   self.resnm[_i] = _rl[5:10]
   self.atomnm[_i] = _rl[10:15]
   self.atomid[_i] = int(_rl[15:20])
   self.xp[_i,0] = float(_rl[20:28])
   self.xp[_i,1] = float(_rl[28:36])
   self.xp[_i,2] = float(_rl[36:44])

  self.box = np.zeros(3)
  _rl = _f.readline()[:-1]

  self.box[0] = float(_rl[0:10])
  self.box[1] = float(_rl[10:20])
  self.box[2] = float(_rl[20:30])




 def show(self, fnm):

  _f= open(fnm,'w')

  _f.write('Generated by GRO module\n')
  _f.write('%5d\n'%self.natom)

  for _i in range(self.natom):

   _f.write('%5d%-5s%5s%5d%8.3f%8.3f%8.3f\n'%\
        (self.resid[_i],\
         self.resnm[_i],\
         self.atomnm[_i],\
         self.atomid[_i],\
         self.xp[_i,0],\
         self.xp[_i,1],\
         self.xp[_i,2]))

  _f.write('%10.5f%10.5f%10.5f\n'%(self.box[0], self.box[1], self.box[2]))

  _f.close()

